FROM golang:1.13.6 as builder
RUN /usr/local/go/bin/go get -u -v github.com/atredispartners/flamingo

FROM gcr.io/distroless/base:latest
COPY --from=builder /go/bin/flamingo /flamingo
CMD ["/flamingo"]
