FROM python:3-alpine

WORKDIR /SprayingToolkit
RUN apk add git gcc musl-dev libffi-dev python3-dev openssl-dev linux-headers libstdc++ g++ libxml2-dev libxslt-dev &&\
    git clone https://github.com/byt3bl33d3r/SprayingToolkit . &&\
    pip install -r requirements.txt

CMD ["/bin/sh"]
