FROM python:3-alpine

WORKDIR /IDontSpeakSSL
RUN apk add git &&\
    git clone https://github.com/BishopFox/IDontSpeakSSL.git --recursive . &&\
    pip install -r requirements.txt

CMD ["/IDontSpeakSSL/IDontSpeakSSL.py"]
ENTRYPOINT ["/IDontSpeakSSL/IDontSpeakSSL.py"]
